apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 2.4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0506d1bcaedf90157
    volumeAttributes:
      dnsname: fs-0506d1bcaedf90157.fsx.us-west-2.amazonaws.com
      mountname: 7vshhbmv
