apiVersion: v1
kind: Pod
metadata:
  name: attach-fsx
spec:
  containers:
  - name: app
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ["-c", "ls -l /fsx"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /fsx
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fsx-claim
