apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: nccl-tests-efa-ring
spec:
  slotsPerWorker: 8
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          imagePullPolicy: Always
          restartPolicy: OnFailure
          containers:
          - image: amrragab8080/aws-efa-nccl-rdma:base-cudnn8-cuda11-ubuntu18.04
            name: nccl-test-launcher
            env:
             - name: LD_LIBRARY_PATH
               value: /opt/amazon/openmpi/lib:/opt/nccl/build/lib:/opt/amazon/efa/lib:/opt/aws-ofi-nccl/install/lib:/usr/local/nvidia/lib:$LD_LIBRARY_PATH
             - name: PATH
               value: $PATH:/opt/amazon/efa/bin
             - name: XLA_FLAGS
               value: "--xla_gpu_cuda_data_dir=/usr/local/cuda"
             - name: TF_XLA_FLAGS
               value: "--tf_xla_cpu_global_jit"
            command:
            - /opt/amazon/openmpi/bin/mpirun
            - --allow-run-as-root
            - --tag-output
            - -np
            - "3"
            - -x
            - PATH
            - -x
            - LD_LIBRARY_PATH
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_ALGO=RING
            - -x
            - FI_EFA_USE_DEVICE_RDMA=1
            - -x
            - RDMAV_FORK_SAFE=1
            - --mca
            - pml
            - ^cm
            - --oversubscribe
            - /opt/aws-ofi-nccl/install/bin/ring

    Worker:
      replicas: 2
      template:
        spec:
          imagePullPolicy: Always
          volumes:
          - name: efa0
            hostPath:
              path: /dev/infiniband/uverbs0
          - name: efa1
            hostPath:
              path: /dev/infiniband/uverbs1
          - name: efa2
            hostPath:
              path: /dev/infiniband/uverbs2
          - name: efa3
            hostPath:
              path: /dev/infiniband/uverbs3
          containers:
          - image: amrragab8080/aws-efa-nccl-rdma:base-cudnn8-cuda11-ubuntu18.04
            name: nccl-worker
            securityContext:
              privileged: true
            resources:
              limits:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
              requests:
                memory: 8000Mi
            volumeMounts:
            - name: efa0
              mountPath: /dev/infiniband/uverbs0
            - name: efa1
              mountPath: /dev/infiniband/uverbs1
            - name: efa2
              mountPath: /dev/infiniband/uverbs2
            - name: efa3
              mountPath: /dev/infiniband/uverbs3
